[build]
  command = "npm run netlify-build"
  publish = ".next"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- . ':(exclude)package-lock.json'"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_TELEMETRY_DISABLED = "1"
  # Добавляем важные переменные окружения для Next.js
  NEXT_RUNTIME = "nodejs"
  NETLIFY_NEXT_PLUGIN_SKIP = "false"

# Используем официальный плагин Next.js с опциями
[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    # Включаем полную трассировку для отладки
    debug = true
    # Убедимся, что все важные файлы создаются и копируются
    includeFiles = [".next/**/*"]
    # Экспериментально увеличиваем лимит для Next.js 15
    nodeBundlerMaximumMemory = "1024"

# Переопределение команды установки
[build.lifecycle]
  onInstall = "npm install --legacy-peer-deps"

# Правильные правила переадресации для Next.js 15
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

[[redirects]]
  from = "/_next/image*"
  to = "/_next/image:splat"
  status = 200

[[redirects]]
  from = "/_next/data/*"
  to = "/_next/data/:splat"
  status = 200

# Это основной редирект для Next.js на Netlify
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-server-handler"
  status = 200
  force = true

# Заголовки ответа
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://cloud.appwrite.io https://*.netlify.app; style-src 'self' 'unsafe-inline'; img-src 'self' blob: data: https://*; media-src 'self' blob: data: https://*; connect-src 'self' https://cloud.appwrite.io https://*.netlify.app https://*; font-src 'self' data:; object-src 'none'; worker-src 'self' blob:;"
    
# Добавляем дополнительные заголовки для JavaScript и CSS
[[headers]]
  for = "/*.js"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 