[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22.14.0"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_TELEMETRY_DISABLED = "1"

# Используем официальный плагин Next.js
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Переопределение команды установки
[build.lifecycle]
  onInstall = "npm install --legacy-peer-deps"

# Удалим старые редиректы, которые могут конфликтовать с маршрутизацией Next.js
# Оставим новую конфигурацию для правильной обработки всех маршрутов

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept" 