[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22.14.0"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_TELEMETRY_DISABLED = "1"

# Используем официальный плагин Next.js
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Переопределение команды установки
[build.lifecycle]
  onInstall = "npm install --legacy-peer-deps"

# Удалим старые редиректы, которые могут конфликтовать с маршрутизацией Next.js
# Оставим новую конфигурацию для правильной обработки всех маршрутов

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://cloud.appwrite.io https://*.netlify.app; style-src 'self' 'unsafe-inline'; img-src 'self' blob: data: https://*; media-src 'self' blob: data: https://*; connect-src 'self' https://cloud.appwrite.io https://*.netlify.app https://*; font-src 'self' data:; object-src 'none'; worker-src 'self' blob:;"
    
# Добавляем дополнительные заголовки для скриптов
[[headers]]
  for = "/*.js"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 